---
title: "ESM206_Assignment4"
author: "Geoffrey Cook"
date: "11/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, include = FALSE}

library(tidyverse)
library(pwr)
library(kableExtra)
library(RColorBrewer)
library(car)
library(vcdExtra)

# load lobster datasets 

lobster_size <- read_csv("lobster_size_abundance.csv")
lobster_traps <- read_csv("lobster_traps.csv")

# fix the lobster size data: select relevant columns, get rid of the zero counts, expand so that each lobster has its own row

lobster_size_tidied <- lobster_size %>% 
  select(YEAR, MONTH, SITE, SIZE, COUNT) %>% 
  filter(SIZE != "-99999") # if the size is -9999, then the count was zero.

lobster_expand <- expand.dft(data.frame(lobster_size_tidied), freq="COUNT")

# fix the lobster traps data into a slightly more manageable data frame
lobster_traps_tidied <- lobster_traps %>% 
  select(YEAR,MONTH,SITE,TRAPS)

```



```{r}

# 1. Lobster abundance and fishing pressure (2012 - 2017)
# Describe trends in lobster abundance (counts) and fishing pressure (trap buoys) at the five locations from 2012 - 2017. Ignore transect information - we are only interested in evaluating abundance and pressure on the order of SITE. Note: you are not expected to use regression here - just think of ways to clearly describe annual totals visually and in text, noting important trends, events and differences.

########## Exploring trends in lobster counts and traps between sites##########
# summary table of some statistics by site called sites_sizes
sites_sizes <- lobster_expand %>% 
  group_by(SITE) %>% 
  summarize(count=n(),
            mean=round(mean(SIZE),2))
sites_sizes

# summary of trap data
site_traps <- lobster_traps_tidied %>% 
  group_by(SITE) %>%
  filter(SITE == "AQUE" | SITE == "NAPL" | SITE == "MOHK" | SITE == "IVEE" | SITE == "CARP") %>% 
  summarize(total= sum(TRAPS))
site_traps

```

```{r}

# 2. Compare mean lobster size by site in 2017
# Compare mean lobster sizes (carapace length (mm)) across the five sites for lobster observations collected in 2017. 

# Exploring the lobster sizes by site
lobster_expand_2017 <- lobster_expand %>% 
    filter(YEAR == "2017")

size_boxplot <- ggplot(lobster_expand_2017, aes(x = SITE, y = SIZE)) +
  geom_boxplot(aes(fill = SITE)) +
  theme(panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(), 
      panel.background = element_blank(),
      axis.line = element_line(colour = "black")) +
  labs(x = "Site Names",
       y = "Carapace Length (mm)", 
       title = "Mean Lobster Size by Site") + # WILL need a fig. caption instead of title in the report
       theme(legend.position = "none") +
  scale_fill_brewer()
size_boxplot


# They LOOK really similar. This feels like a job for... ANOVA!


```
```{r}
# THE ANOVA TEST
# - Independent observations
# - Equal variances (Levene's test)
# - Normality (histograms and qq plots)
# Only after exploring these things can we decide whether or not an ANOVA is appropriate to test these means. 

lobster_size_qq <- ggplot(lobster_expand_2017, aes(sample=SIZE))+
  geom_qq() +
  facet_wrap(~SITE)
lobster_size_qq

lobster_size_hist <- ggplot(lobster_expand_2017, aes(x=SIZE)) +
  geom_histogram() +
  facet_wrap(~SITE)
lobster_size_hist

# Test for equal variances
# If the largest sample variance is less than 4x greater than the smallest sample variance, then these are close enough to consider variances equal (an ANOVA is robust enough for this)

variances <- lobster_expand_2017 %>% 
  group_by(SITE) %>% 
  summarize(
    variance=var(SIZE)
  )
variances
# The largest variance is not more than 4x greater than the smallest variance! Yay

# YAY now we can ANOVA
# H0: the means across all groups are equal
# H1: the means between at least two groups are different

lobster_size_2017_aov <- aov(SIZE ~ SITE, data= lobster_expand_2017)
summary(lobster_size_2017_aov)

# p=0.0085.... interesting
# So which ones are different, then?!?!
# Tukeys HSD

lobster_size_2017_ph <- TukeyHSD(lobster_size_2017_aov  )
lobster_size_2017_ph

# sig differences between NAPL-CARP, NAPL-IVEE at alpha=.05
```



```{r}

# 3. Changes in lobster size at MPA and non-MPA sites (comparing only 2012 and 2017 sizes)
# From the data description (http://sbc.lternet.edu/cgi-bin/showDataset.cgi?docid=knb-lter-sbc.77):
# “Data on abundance, size and fishing pressure of California spiny lobster (Panulirus interruptus) are collected along the mainland coast of the Santa Barbara Channel. Spiny lobsters are an important predator in giant kelp forests off southern California. Two SBC LTER study reefs are located in or near the California Fish and Game Network of Marine Protected Areas (MPA), Naples and Isla Vista, both established as MPAs on 2012-01-01. MPAs provide a unique opportunity to investigate the effects of fishing on kelp forest community dynamics. Sampling began in 2012 and is ongoing.”
# At Isla Vista and Naples Reef, the two protected MPA sites (with zero fishing pressure), how do lobster sizes in 2012 and 2017 compare? At the non-MPA sites?


# New df looking at MPAs
MPA_sizes <- lobster_expand %>% 
  mutate(MPA= case_when(.$SITE== "IVEE" | .$SITE =="NAPL"~ "Y",
                        TRUE~ "N"))

# t-test craziness-- comparing 2012 to 2017 mean carapace size at each of the 5 sites

# but first, checking for normality/generally looking at the data

lobster_expand_2012 <- lobster_expand %>% 
    filter(YEAR == "2012") 

lobster_size_2012_qq <- ggplot(lobster_expand_2012, aes(sample=SIZE))+
  geom_qq() +
  facet_wrap(~SITE)
lobster_size_2012_qq

lobster_size_2012_hist <- ggplot(lobster_expand_2012, aes(x=SIZE)) +
  geom_histogram() +
  facet_wrap(~SITE)
lobster_size_2012_hist

# Ok, they're mostly normal-ish (except for the one with 6 data points, so yikes!)
# Now for some t-tests!
# CARP, IVEE, AQUE, MOHK, NAPL


#create new carp dataframes
carp_2012 <- lobster_expand_2012 %>% 
  filter (SITE =="CARP")
carp_2017 <- lobster_expand_2017 %>% 
  filter (SITE =="CARP")
#check for equal variance
CARP_f_test <- var.test(carp_2012$SIZE, carp_2017$SIZE)
CARP_f_test
#variances are equal! run t.test with va.equal=TRUE
CARP_size_t <- t.test (lobster_expand_2012$SIZE, lobster_expand_2017$SIZE, var.equal=TRUE)
CARP_size_t
#p=0.07794

#create new IVEE dataframes
ivee_2012 <- lobster_expand_2012 %>% 
  filter (SITE =="IVEE")
ivee_2017 <- lobster_expand_2017 %>% 
  filter (SITE =="IVEE")
#check for equal variance
IVEE_f_test <- var.test(ivee_2012$SIZE,ivee_2017$SIZE)
IVEE_f_test
#variances are equal! run t.test with va.equal=TRUE
IVEE_size_t <- t.test (ivee_2012$SIZE, ivee_2017$SIZE, var.equal=TRUE)
IVEE_size_t
# p= 0.0599

#create new AQUE dataframes
aque_2012 <- lobster_expand_2012 %>% 
  filter (SITE =="AQUE")
aque_2017 <- lobster_expand_2017 %>% 
  filter (SITE =="AQUE")
#check for equal variance
AQUE_f_test <- var.test(aque_2012$SIZE,aque_2017$SIZE)
AQUE_f_test
#variances are equal! run t.test with va.equal=TRUE
AQUE_size_t <- t.test (aque_2012$SIZE, aque_2017$SIZE, var.equal=TRUE)
AQUE_size_t
#p=0.2097

#create new MOHK dataframes
mohk_2012 <- lobster_expand_2012 %>% 
  filter (SITE =="MOHK")
mohk_2017 <- lobster_expand_2017 %>% 
  filter (SITE =="MOHK")
#check for equal variance
MOHK_f_test <- var.test(mohk_2012$SIZE,mohk_2017$SIZE)
MOHK_f_test
#variances are equal! run t.test with va.equal=TRUE
MOHK_size_t <- t.test (mohk_2012$SIZE, mohk_2017$SIZE, var.equal=TRUE)
MOHK_size_t
#p< 0.001 

napl_2012 <- lobster_expand_2012 %>% 
  filter (SITE =="NAPL")
napl_2017 <- lobster_expand_2017 %>% 
  filter (SITE =="NAPL")
#check for equal variance
NAPL_f_test <- var.test(napl_2012$SIZE,napl_2017$SIZE)
NAPL_f_test
#variances are equal! run t.test with va.equal=TRUE
NAPL_size_t <- t.test (napl_2012$SIZE, napl_2017$SIZE, var.equal=TRUE)
NAPL_size_t
#p=0.5002

```

```{r}
# What is the proportion of lobsters above the legal length (82.6 mm)? Compare that amongst the 5 sites.

# chi-square test
# H0: no association between site and lobsters being legal size (independence)
# H1: there is an association between the variables (non-independence)


# lobsters at each site, above and below legal lengths
# prepating data for the chi-squared test
legal_lobsters <- lobster_expand_2017 %>% 
  group_by(SITE) %>% 
  mutate("LEGAL"= case_when(SIZE > 82.6 ~ "Y", TRUE ~ "N")) %>% 
  count(LEGAL) %>% 
  spread(LEGAL, n) %>% 
  ungroup() %>% 
  select (-SITE)

rownames(legal_lobsters) <- c("AQUE", "CARP","IVEE","MOHK","NAPL")

#calculate proportions in a prop.table
legal_prop <- prop.table(as.matrix(legal_lobsters), 1)
legal_prop

legal_chisquare <- chisq.test(legal_lobsters)
legal_chisquare

# p-value = 0.0009864

```

